
title: "Data organisation practices"
repository:  <USERNAME>/<PROJECT> # See https://help.github.com/articles/repository-metadata-on-github-pages/.
#repository:  NBISweden/module-organising-data-dm-practices
email: "data@nbis.se"
nbis_site: "https://nbis.se/"
carpentry: nbis
remote_theme: NBISweden/styles-dm-practices@canvas

collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page


# Files and directories that are not to be copied.
exclude:
  - Gemfile*
  - environment.yml
  - README.md
  

highlighter: rouge
